CREATE TABLE gold_transactions (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clanId bigint,
    timestamp timestamp,
    cause text,
    causeId bigint,
    goldBefore bigint,
    goldUpdateAmount integer,
    goldAfter bigint
);